/*
 *   IMU_Sfcn_mex.c Simple C-MEX S-function for function call.
 *
 *   ABSTRACT:
 *     The purpose of this sfunction is to call a simple legacy
 *     function during simulation:
 *
 *        void MDL_IMU_step(IMU_Packets y1[1], int32 y2[1])
 *
 *   Simulink version           : 8.3 (R2014a) 27-Dec-2013
 *   C source code generated on : 28-Mar-2014 14:56:16

 * THIS S-FUNCTION IS GENERATED BY THE LEGACY CODE TOOL AND MAY NOT WORK IF MODIFIED

 */

/*
   %%%-MATLAB_Construction_Commands_Start
   def = legacy_code('initialize');
   def.SFunctionName = 'IMU_Sfcn_mex';
   def.InitializeConditionsFcnSpec = 'void MDL_IMU_start()';
   def.OutputFcnSpec = 'void MDL_IMU_step(IMU_Packets y1[1], int32 y2[1])';
   def.TerminateFcnSpec = 'void MDL_IMU_term()';
   def.SourceFiles = {'IMU_Navdata_Wrapper.c'};
   def.SampleTime = 'parameterized';
   def.Options.useTlcWithAccel = false;
   legacy_code('sfcn_cmex_generate', def);
   legacy_code('compile', def);
   %%%-MATLAB_Construction_Commands_End
 */

/*
 * Must specify the S_FUNCTION_NAME as the name of the S-function.
 */
#define S_FUNCTION_NAME                IMU_Sfcn_mex
#define S_FUNCTION_LEVEL               2

/*
 * Need to include simstruc.h for the definition of the SimStruct and
 * its associated macro definitions.
 */
#include "simstruc.h"
#include <string.h>

/*
 * Specific header file(s) required for data types declarations.
 */
#include "IMU_Navdata.h"

/*
 * Code Generation Environment flag (simulation or standalone target).
 */
static int_T isSimulationTarget;

#define EDIT_OK(S, P_IDX) \
 (!((ssGetSimMode(S)==SS_SIMMODE_SIZES_CALL_ONLY) && mxIsEmpty(ssGetSFcnParam(S, P_IDX))))
#define SAMPLE_TIME                    (ssGetSFcnParam(S, 0))
#define isDWorkNeeded                  ((!((ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) && isSimulationTarget==0)) || ssIsRapidAcceleratorActive(S))

/*
 * Utility function prototypes.
 */
static bool IsRealMatrix(const mxArray *m);
static void CheckDataTypes(SimStruct *S);
static int_T GetRTWEnvironmentMode(SimStruct *S);

#define MDL_CHECK_PARAMETERS
#if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)

/* Function: mdlCheckParameters ===========================================
 * Abstract:
 *    mdlCheckParameters verifies new parameter settings whenever parameter
 *    change or are re-evaluated during a simulation. When a simulation is
 *    running, changes to S-function parameters can occur at any time during
 *    the simulation loop.
 */
static void mdlCheckParameters(SimStruct *S)
{
  /*
   * Check the parameter 1 (sample time)
   */
  if EDIT_OK(S, 0) {
    real_T *sampleTime = NULL;
    mwSize stArraySize = mxGetM(SAMPLE_TIME) * mxGetN(SAMPLE_TIME);

    /* Sample time must be a real scalar value or 2 element array. */
    if (IsRealMatrix(SAMPLE_TIME) &&
        (stArraySize == 1 || stArraySize == 2) ) {
      sampleTime = (real_T *) mxGetPr(SAMPLE_TIME);
    } else {
      ssSetErrorStatus(S,
                       "Invalid sample time. Sample time must be a real scalar value or an array of two real values.");
      return;
    }

    if (sampleTime[0] < 0.0 && sampleTime[0] != -1.0) {
      ssSetErrorStatus(S,
                       "Invalid sample time. Period must be non-negative or -1 (for inherited).");
      return;
    }

    if (stArraySize == 2 && sampleTime[0] > 0.0 &&
        sampleTime[1] >= sampleTime[0]) {
      ssSetErrorStatus(S,
                       "Invalid sample time. Offset must be smaller than period.");
      return;
    }

    if (stArraySize == 2 && sampleTime[0] == -1.0 && sampleTime[1] != 0.0) {
      ssSetErrorStatus(S,
                       "Invalid sample time. When period is -1, offset must be 0.");
      return;
    }

    if (stArraySize == 2 && sampleTime[0] == 0.0 &&
        !(sampleTime[1] == 1.0)) {
      ssSetErrorStatus(S,
                       "Invalid sample time. When period is 0, offset must be 1.");
      return;
    }
  }
}

#endif

/* Function: mdlInitializeSizes ===========================================
 * Abstract:
 *    The sizes information is used by Simulink to determine the S-function
 *    block's characteristics (number of inputs, outputs, states, etc.).
 */
static void mdlInitializeSizes(SimStruct *S)
{
  /*
   * Get the value returned by rtwenvironmentmode(modelName)
   */
  if (ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) {
    isSimulationTarget = GetRTWEnvironmentMode(S);
    if (isSimulationTarget==-1) {
      ssSetErrorStatus(S,
                       "Unable to determine a valid code generation environment mode.");
      return;
    }

    isSimulationTarget |= ssRTWGenIsModelReferenceSimTarget(S);
  }

  /* Number of expected parameters */
  ssSetNumSFcnParams(S, 1);

#if defined(MATLAB_MEX_FILE)

  if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
    /*
     * If the number of expected input parameters is not equal
     * to the number of parameters entered in the dialog box return.
     * Simulink will generate an error indicating that there is a
     * parameter mismatch.
     */
    mdlCheckParameters(S);
    if (ssGetErrorStatus(S) != NULL) {
      return;
    }
  } else {
    /* Return if number of expected != number of actual parameters */
    return;
  }

#endif

  /* Set the parameter's tunability */
  ssSetSFcnParamTunable(S, 0, 0);

  /*
   * Set the number of pworks.
   */
  ssSetNumPWork(S, 0);

  /*
   * Set the number of dworks.
   */
  if (! isDWorkNeeded) {
    if (!ssSetNumDWork(S, 0))
      return;
  } else {
    if (!ssSetNumDWork(S, 3))
      return;
  }

  if (isDWorkNeeded) {
    /*
     * Configure the dwork 1 (y1BUS)
     */
#if defined(MATLAB_MEX_FILE)

    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
      DTypeId dataTypeIdReg;
      ssRegisterTypeFromNamedObject(S, "IMU_Packets", &dataTypeIdReg);
      if (dataTypeIdReg == INVALID_DTYPE_ID)
        return;
      ssSetDWorkDataType(S, 0, dataTypeIdReg);
    }

#endif

    ssSetDWorkUsageType(S, 0, SS_DWORK_USED_AS_DWORK);
    ssSetDWorkName(S, 0, "y1BUS");
    ssSetDWorkWidth(S, 0, DYNAMICALLY_SIZED);
    ssSetDWorkComplexSignal(S, 0, COMPLEX_NO);

    /*
     * Configure the dwork 2 (__dtSizeInfo)
     */
    ssSetDWorkDataType(S, 1, SS_INT32);
    ssSetDWorkUsageType(S, 1, SS_DWORK_USED_AS_DWORK);
    ssSetDWorkName(S, 1, "dtSizeInfo");
    ssSetDWorkWidth(S, 1, 5);
    ssSetDWorkComplexSignal(S, 1, COMPLEX_NO);

    /*
     * Configure the dwork 3 (__dtBusInfo)
     */
    ssSetDWorkDataType(S, 2, SS_INT32);
    ssSetDWorkUsageType(S, 2, SS_DWORK_USED_AS_DWORK);
    ssSetDWorkName(S, 2, "dtBusInfo");
    ssSetDWorkWidth(S, 2, 56);
    ssSetDWorkComplexSignal(S, 2, COMPLEX_NO);
  }

  /*
   * Set the number of input ports.
   */
  if (!ssSetNumInputPorts(S, 0))
    return;

  /*
   * Set the number of output ports.
   */
  if (!ssSetNumOutputPorts(S, 2))
    return;

  /*
   * Configure the output port 1
   */
#if defined(MATLAB_MEX_FILE)

  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
    DTypeId dataTypeIdReg;
    ssRegisterTypeFromNamedObject(S, "IMU_Packets", &dataTypeIdReg);
    if (dataTypeIdReg == INVALID_DTYPE_ID)
      return;
    ssSetOutputPortDataType(S, 0, dataTypeIdReg);
  }

#endif

  ssSetBusOutputObjectName(S, 0, (void *)"IMU_Packets");
  ssSetBusOutputAsStruct(S, 0, 1);
  ssSetOutputPortWidth(S, 0, 1);
  ssSetOutputPortComplexSignal(S, 0, COMPLEX_NO);
  ssSetOutputPortOptimOpts(S, 0, SS_REUSABLE_AND_LOCAL);
  ssSetOutputPortOutputExprInRTW(S, 0, 0);

  /*
   * Configure the output port 2
   */
  ssSetOutputPortDataType(S, 1, SS_INT32);
  ssSetOutputPortWidth(S, 1, 1);
  ssSetOutputPortComplexSignal(S, 1, COMPLEX_NO);
  ssSetOutputPortOptimOpts(S, 1, SS_REUSABLE_AND_LOCAL);
  ssSetOutputPortOutputExprInRTW(S, 1, 0);

  /*
   * Register reserved identifiers to avoid name conflict
   */
  if (ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) {
    /*
     * Register reserved identifier for InitializeConditionsFcnSpec
     */
    ssRegMdlInfo(S, "MDL_IMU_start", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));

    /*
     * Register reserved identifier for OutputFcnSpec
     */
    ssRegMdlInfo(S, "MDL_IMU_step", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));

    /*
     * Register reserved identifier for TerminateFcnSpec
     */
    ssRegMdlInfo(S, "MDL_IMU_term", MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));

    /*
     * Register reserved identifier for wrappers
     */
    if (isSimulationTarget) {
      /*
       * Register reserved identifier for InitializeConditionsFcnSpec for SimulationTarget
       */
      ssRegMdlInfo(S, "IMU_Sfcn_mex_wrapper_initialize_conditions",
                   MDL_INFO_ID_RESERVED, 0, 0, ssGetPath(S));

      /*
       * Register reserved identifier for OutputFcnSpec for SimulationTarget
       */
      ssRegMdlInfo(S, "IMU_Sfcn_mex_wrapper_output", MDL_INFO_ID_RESERVED, 0, 0,
                   ssGetPath(S));

      /*
       * Register reserved identifier for TerminateFcnSpec for SimulationTarget
       */
      ssRegMdlInfo(S, "IMU_Sfcn_mex_wrapper_terminate", MDL_INFO_ID_RESERVED, 0,
                   0, ssGetPath(S));
    }
  }

  /*
   * This S-function can be used in referenced model simulating in normal mode.
   */
  ssSetModelReferenceNormalModeSupport(S, MDL_START_AND_MDL_PROCESS_PARAMS_OK);

  /*
   * Set the number of sample time.
   */
  ssSetNumSampleTimes(S, 1);

  /*
   * All options have the form SS_OPTION_<name> and are documented in
   * matlabroot/simulink/include/simstruc.h. The options should be
   * bitwise or'd together as in
   *   ssSetOptions(S, (SS_OPTION_name1 | SS_OPTION_name2))
   */
  ssSetOptions(S,
               SS_OPTION_CAN_BE_CALLED_CONDITIONALLY |
               SS_OPTION_EXCEPTION_FREE_CODE |
               SS_OPTION_WORKS_WITH_CODE_REUSE |
               SS_OPTION_SFUNCTION_INLINED_FOR_RTW |
               SS_OPTION_DISALLOW_CONSTANT_SAMPLE_TIME);

#if defined(MATLAB_MEX_FILE)

  if ((ssGetSimMode(S)!=SS_SIMMODE_SIZES_CALL_ONLY) && !ssRTWGenIsCodeGen(S)) {
    /* Verify Data Type consistency with specification */
    CheckDataTypes(S);
  }

#endif

  ssSetSimulinkVersionGeneratedIn(S, "8.3");
}

/* Function: mdlInitializeSampleTimes =====================================
 * Abstract:
 *    This function is used to specify the sample time(s) for your
 *    S-function. You must register the same number of sample times as
 *    specified in ssSetNumSampleTimes.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  real_T * sampleTime = (real_T*) (mxGetPr(SAMPLE_TIME));
  mwSize stArraySize = mxGetM(SAMPLE_TIME) * mxGetN(SAMPLE_TIME);
  ssSetSampleTime(S, 0, sampleTime[0]);
  if (stArraySize == 1) {
    ssSetOffsetTime(S, 0, (sampleTime[0] == CONTINUOUS_SAMPLE_TIME?
      FIXED_IN_MINOR_STEP_OFFSET: 0.0));
  } else {
    ssSetOffsetTime(S, 0, sampleTime[1]);
  }

#if defined(ssSetModelReferenceSampleTimeDefaultInheritance)

  ssSetModelReferenceSampleTimeDefaultInheritance(S);

#endif

}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

/* Function: mdlSetWorkWidths =============================================
 * Abstract:
 *      The optional method, mdlSetWorkWidths is called after input port
 *      width, output port width, and sample times of the S-function have
 *      been determined to set any state and work vector sizes which are
 *      a function of the input, output, and/or sample times.
 *
 *      Run-time parameters are registered in this method using methods
 *      ssSetNumRunTimeParams, ssSetRunTimeParamInfo, and related methods.
 */
static void mdlSetWorkWidths(SimStruct *S)
{
  /* Set the width of DWork(s) used for marshalling the IOs */
  if (!((ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) &&
        isSimulationTarget==0)) {
    /* Update dwork 1 (y1BUS) */
    ssSetDWorkWidth(S, 0, ssGetOutputPortWidth(S, 0));
  }
}

#endif

#define MDL_START
#if defined(MDL_START)

/* Function: mdlStart =====================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
  if (!((ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) &&
        isSimulationTarget==0)) {
    /*
     * Access bus/struct information
     */
    int32_T *__dtSizeInfo = (int32_T *) ssGetDWork(S, 1);
    int32_T *__dtBusInfo = (int32_T *) ssGetDWork(S, 2);

    /* Get common data type Id */
    DTypeId __IMU_PacketsId = ssGetDataTypeId(S, "IMU_Packets");
    DTypeId __uint16Id = ssGetDataTypeId(S, "uint16");
    DTypeId __int16Id = ssGetDataTypeId(S, "int16");
    DTypeId __uint32Id = ssGetDataTypeId(S, "uint32");
    DTypeId __int32Id = ssGetDataTypeId(S, "int32");

    /* Get common data type size */
    __dtSizeInfo[0] = ssGetDataTypeSize(S, __IMU_PacketsId);
    __dtSizeInfo[1] = ssGetDataTypeSize(S, __uint16Id);
    __dtSizeInfo[2] = ssGetDataTypeSize(S, __int16Id);
    __dtSizeInfo[3] = ssGetDataTypeSize(S, __uint32Id);
    __dtSizeInfo[4] = ssGetDataTypeSize(S, __int32Id);

    /* Get information for accessing IMU_Packets.taille */
    __dtBusInfo[0] = ssGetBusElementOffset(S, __IMU_PacketsId, 0);
    __dtBusInfo[1] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.nu_trame */
    __dtBusInfo[2] = ssGetBusElementOffset(S, __IMU_PacketsId, 1);
    __dtBusInfo[3] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.ax */
    __dtBusInfo[4] = ssGetBusElementOffset(S, __IMU_PacketsId, 2);
    __dtBusInfo[5] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.ay */
    __dtBusInfo[6] = ssGetBusElementOffset(S, __IMU_PacketsId, 3);
    __dtBusInfo[7] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.az */
    __dtBusInfo[8] = ssGetBusElementOffset(S, __IMU_PacketsId, 4);
    __dtBusInfo[9] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.vx */
    __dtBusInfo[10] = ssGetBusElementOffset(S, __IMU_PacketsId, 5);
    __dtBusInfo[11] = __dtSizeInfo[2];

    /* Get information for accessing IMU_Packets.vy */
    __dtBusInfo[12] = ssGetBusElementOffset(S, __IMU_PacketsId, 6);
    __dtBusInfo[13] = __dtSizeInfo[2];

    /* Get information for accessing IMU_Packets.vz */
    __dtBusInfo[14] = ssGetBusElementOffset(S, __IMU_PacketsId, 7);
    __dtBusInfo[15] = __dtSizeInfo[2];

    /* Get information for accessing IMU_Packets.temperature_acc */
    __dtBusInfo[16] = ssGetBusElementOffset(S, __IMU_PacketsId, 8);
    __dtBusInfo[17] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.temperature_gyro */
    __dtBusInfo[18] = ssGetBusElementOffset(S, __IMU_PacketsId, 9);
    __dtBusInfo[19] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.ultrasound */
    __dtBusInfo[20] = ssGetBusElementOffset(S, __IMU_PacketsId, 10);
    __dtBusInfo[21] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.us_debut_echo */
    __dtBusInfo[22] = ssGetBusElementOffset(S, __IMU_PacketsId, 11);
    __dtBusInfo[23] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.us_fin_echo */
    __dtBusInfo[24] = ssGetBusElementOffset(S, __IMU_PacketsId, 12);
    __dtBusInfo[25] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.us_association_echo */
    __dtBusInfo[26] = ssGetBusElementOffset(S, __IMU_PacketsId, 13);
    __dtBusInfo[27] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.us_distance_echo */
    __dtBusInfo[28] = ssGetBusElementOffset(S, __IMU_PacketsId, 14);
    __dtBusInfo[29] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.us_curve_time */
    __dtBusInfo[30] = ssGetBusElementOffset(S, __IMU_PacketsId, 15);
    __dtBusInfo[31] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.us_curve_value */
    __dtBusInfo[32] = ssGetBusElementOffset(S, __IMU_PacketsId, 16);
    __dtBusInfo[33] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.us_curve_ref */
    __dtBusInfo[34] = ssGetBusElementOffset(S, __IMU_PacketsId, 17);
    __dtBusInfo[35] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.nb_echo */
    __dtBusInfo[36] = ssGetBusElementOffset(S, __IMU_PacketsId, 18);
    __dtBusInfo[37] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.sum_echo */
    __dtBusInfo[38] = ssGetBusElementOffset(S, __IMU_PacketsId, 19);
    __dtBusInfo[39] = __dtSizeInfo[3];

    /* Get information for accessing IMU_Packets.gradient */
    __dtBusInfo[40] = ssGetBusElementOffset(S, __IMU_PacketsId, 20);
    __dtBusInfo[41] = __dtSizeInfo[2];

    /* Get information for accessing IMU_Packets.flag_echo_ini */
    __dtBusInfo[42] = ssGetBusElementOffset(S, __IMU_PacketsId, 21);
    __dtBusInfo[43] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.pressure */
    __dtBusInfo[44] = ssGetBusElementOffset(S, __IMU_PacketsId, 22);
    __dtBusInfo[45] = __dtSizeInfo[4];

    /* Get information for accessing IMU_Packets.temperature_pressure */
    __dtBusInfo[46] = ssGetBusElementOffset(S, __IMU_PacketsId, 23);
    __dtBusInfo[47] = __dtSizeInfo[1];

    /* Get information for accessing IMU_Packets.mx */
    __dtBusInfo[48] = ssGetBusElementOffset(S, __IMU_PacketsId, 24);
    __dtBusInfo[49] = __dtSizeInfo[2];

    /* Get information for accessing IMU_Packets.my */
    __dtBusInfo[50] = ssGetBusElementOffset(S, __IMU_PacketsId, 25);
    __dtBusInfo[51] = __dtSizeInfo[2];

    /* Get information for accessing IMU_Packets.mz */
    __dtBusInfo[52] = ssGetBusElementOffset(S, __IMU_PacketsId, 26);
    __dtBusInfo[53] = __dtSizeInfo[2];

    /* Get information for accessing IMU_Packets.chksum */
    __dtBusInfo[54] = ssGetBusElementOffset(S, __IMU_PacketsId, 27);
    __dtBusInfo[55] = __dtSizeInfo[1];
  }
}

#endif

#define MDL_INITIALIZE_CONDITIONS
#if defined(MDL_INITIALIZE_CONDITIONS)

/* Function: mdlInitializeConditions ======================================
 * Abstract:
 *    In this function, you should initialize the states for your S-function block.
 *    You can also perform any other initialization activities that your
 *    S-function may require. Note, this routine will be called at the
 *    start of simulation and if it is present in an enabled subsystem
 *    configured to reset states, it will be call when the enabled subsystem
 *    restarts execution to reset the states.
 */
static void mdlInitializeConditions(SimStruct *S)
{
  if (!((ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) &&
        isSimulationTarget==0)) {
    /*
     * Access bus/struct information
     */
    int32_T *__dtSizeInfo = (int32_T *) ssGetDWork(S, 1);
    int32_T *__dtBusInfo = (int32_T *) ssGetDWork(S, 2);

    /*
     * Call the legacy code function
     */
    MDL_IMU_start();
  }
}

#endif

/* Function: mdlOutputs ===================================================
 * Abstract:
 *    In this function, you compute the outputs of your S-function
 *    block. Generally outputs are placed in the output vector(s),
 *    ssGetOutputPortSignal.
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  if (!((ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) &&
        isSimulationTarget==0)) {
    /*
     * Access bus/struct information
     */
    int32_T *__dtSizeInfo = (int32_T *) ssGetDWork(S, 1);
    int32_T *__dtBusInfo = (int32_T *) ssGetDWork(S, 2);

    /*
     * Get access to Parameter/Input/Output/DWork/size information
     */
    char *y1 = (char *) ssGetOutputPortSignal(S, 0);
    int32_T *y2 = (int32_T *) ssGetOutputPortSignal(S, 1);

    /*
     * Locally declared variable(s)
     */
    IMU_Packets *__y1BUS = (IMU_Packets *) ssGetDWork(S, 0);

    /*
     * Call the legacy code function
     */
    MDL_IMU_step( __y1BUS, y2);

    /*
     * Assign the Legacy Structure __y1BUS to the Simulink Structure y1
     */
    (void) memcpy(y1 + __dtBusInfo[0], &__y1BUS[0].taille
                  , __dtBusInfo[1]);
    (void) memcpy(y1 + __dtBusInfo[2], &__y1BUS[0].nu_trame
                  , __dtBusInfo[3]);
    (void) memcpy(y1 + __dtBusInfo[4], &__y1BUS[0].ax
                  , __dtBusInfo[5]);
    (void) memcpy(y1 + __dtBusInfo[6], &__y1BUS[0].ay
                  , __dtBusInfo[7]);
    (void) memcpy(y1 + __dtBusInfo[8], &__y1BUS[0].az
                  , __dtBusInfo[9]);
    (void) memcpy(y1 + __dtBusInfo[10], &__y1BUS[0].vx
                  , __dtBusInfo[11]);
    (void) memcpy(y1 + __dtBusInfo[12], &__y1BUS[0].vy
                  , __dtBusInfo[13]);
    (void) memcpy(y1 + __dtBusInfo[14], &__y1BUS[0].vz
                  , __dtBusInfo[15]);
    (void) memcpy(y1 + __dtBusInfo[16], &__y1BUS[0].temperature_acc
                  , __dtBusInfo[17]);
    (void) memcpy(y1 + __dtBusInfo[18], &__y1BUS[0].temperature_gyro
                  , __dtBusInfo[19]);
    (void) memcpy(y1 + __dtBusInfo[20], &__y1BUS[0].ultrasound
                  , __dtBusInfo[21]);
    (void) memcpy(y1 + __dtBusInfo[22], &__y1BUS[0].us_debut_echo
                  , __dtBusInfo[23]);
    (void) memcpy(y1 + __dtBusInfo[24], &__y1BUS[0].us_fin_echo
                  , __dtBusInfo[25]);
    (void) memcpy(y1 + __dtBusInfo[26], &__y1BUS[0].us_association_echo
                  , __dtBusInfo[27]);
    (void) memcpy(y1 + __dtBusInfo[28], &__y1BUS[0].us_distance_echo
                  , __dtBusInfo[29]);
    (void) memcpy(y1 + __dtBusInfo[30], &__y1BUS[0].us_curve_time
                  , __dtBusInfo[31]);
    (void) memcpy(y1 + __dtBusInfo[32], &__y1BUS[0].us_curve_value
                  , __dtBusInfo[33]);
    (void) memcpy(y1 + __dtBusInfo[34], &__y1BUS[0].us_curve_ref
                  , __dtBusInfo[35]);
    (void) memcpy(y1 + __dtBusInfo[36], &__y1BUS[0].nb_echo
                  , __dtBusInfo[37]);
    (void) memcpy(y1 + __dtBusInfo[38], &__y1BUS[0].sum_echo
                  , __dtBusInfo[39]);
    (void) memcpy(y1 + __dtBusInfo[40], &__y1BUS[0].gradient
                  , __dtBusInfo[41]);
    (void) memcpy(y1 + __dtBusInfo[42], &__y1BUS[0].flag_echo_ini
                  , __dtBusInfo[43]);
    (void) memcpy(y1 + __dtBusInfo[44], &__y1BUS[0].pressure
                  , __dtBusInfo[45]);
    (void) memcpy(y1 + __dtBusInfo[46], &__y1BUS[0].temperature_pressure
                  , __dtBusInfo[47]);
    (void) memcpy(y1 + __dtBusInfo[48], &__y1BUS[0].mx
                  , __dtBusInfo[49]);
    (void) memcpy(y1 + __dtBusInfo[50], &__y1BUS[0].my
                  , __dtBusInfo[51]);
    (void) memcpy(y1 + __dtBusInfo[52], &__y1BUS[0].mz
                  , __dtBusInfo[53]);
    (void) memcpy(y1 + __dtBusInfo[54], &__y1BUS[0].chksum
                  , __dtBusInfo[55]);
  }
}

/* Function: mdlTerminate =================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.
 */
static void mdlTerminate(SimStruct *S)
{
  if (!((ssRTWGenIsCodeGen(S) || ssGetSimMode(S)==SS_SIMMODE_EXTERNAL) &&
        isSimulationTarget==0)) {
    /*
     * Access bus/struct information
     */
    int32_T *__dtSizeInfo = (int32_T *) ssGetDWork(S, 1);
    int32_T *__dtBusInfo = (int32_T *) ssGetDWork(S, 2);

    /*
     * Call the legacy code function
     */
    MDL_IMU_term();
  }
}

#define MDL_RTW
#if defined(MATLAB_MEX_FILE) && defined(MDL_RTW)

/* Function: mdlRTW =======================================================
 * Abstract:
 *    This function is called when Simulink Coder is generating
 *    the model.rtw file.
 */
static void mdlRTW(SimStruct *S)
{
}

#endif

/* Function: IsRealMatrix =================================================
 * Abstract:
 *      Verify that the mxArray is a real (double) finite matrix
 */
bool IsRealMatrix(const mxArray *m)
{
  if (mxIsNumeric(m) &&
      mxIsDouble(m) &&
      !mxIsLogical(m) &&
      !mxIsComplex(m) &&
      !mxIsSparse(m) &&
      !mxIsEmpty(m) &&
      mxGetNumberOfDimensions(m) == 2) {
    real_T *data = mxGetPr(m);
    mwSize numEl = mxGetNumberOfElements(m);
    mwSize i;
    for (i = 0; i < numEl; i++) {
      if (!mxIsFinite(data[i])) {
        return(false);
      }
    }

    return(true);
  } else {
    return(false);
  }
}

/* Function: CheckDataTypes =============================================
 * Abstract:
 *    CheckDataTypes verifies data types consistency between the data type
 *    definition used when this S-Function was generated and the data type
 *    used when calling the S-Function.
 */
static void CheckDataTypes(SimStruct *S)
{
  /*
   * Access data type information
   */
  slDataTypeAccess *dta = ssGetDataTypeAccess(S);
  const char *bpath = ssGetPath(S);
  DTypeId __IMU_PacketsId = ssGetDataTypeId(S, "IMU_Packets");
  DTypeId __uint16Id = ssGetDataTypeId(S, "uint16");
  DTypeId __int16Id = ssGetDataTypeId(S, "int16");
  DTypeId __uint32Id = ssGetDataTypeId(S, "uint32");
  DTypeId __int32Id = ssGetDataTypeId(S, "int32");

  /* Verify Bus/StructType 'IMU_Packets', specification */
  if (ssGetNumBusElements(S, __IMU_PacketsId)!=28) {
    ssSetErrorStatus(S,
                     "The Bus/StructType 'IMU_Packets' must have 28 elements.");
    return;
  }

  {
    int_T dimIdx, width, *dims;

    /* Verify Bus/Struct element 'IMU_Packets.taille' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 0), "taille")!=0)
    {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'taille' in position 1.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.taille' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 0)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.taille' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.taille' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 0);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId, 0);
         dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.taille' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.taille' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 0)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.taille' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.nu_trame' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 1), "nu_trame")
        !=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'nu_trame' in position 2.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.nu_trame' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 1)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.nu_trame' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.nu_trame' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 1);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId, 1);
         dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.nu_trame' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.nu_trame' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 1)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.nu_trame' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ax' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 2), "ax")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'ax' in position 3.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ax' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 2)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.ax' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ax' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 2);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId, 2);
         dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.ax' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ax' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 2)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.ax' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ay' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 3), "ay")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'ay' in position 4.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ay' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 3)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.ay' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ay' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 3);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId, 3);
         dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.ay' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ay' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 3)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.ay' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.az' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 4), "az")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'az' in position 5.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.az' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 4)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.az' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.az' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 4);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId, 4);
         dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.az' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.az' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 4)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.az' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vx' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 5), "vx")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'vx' in position 6.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vx' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 5)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "int16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.vx' must have the same data type storage Id as an 'int16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vx' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 5);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId, 5);
         dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.vx' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vx' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 5)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.vx' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vy' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 6), "vy")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'vy' in position 7.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vy' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 6)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "int16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.vy' must have the same data type storage Id as an 'int16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vy' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 6);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId, 6);
         dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.vy' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vy' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 6)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.vy' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vz' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 7), "vz")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'vz' in position 8.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vz' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 7)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "int16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.vz' must have the same data type storage Id as an 'int16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vz' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 7);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId, 7);
         dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.vz' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.vz' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 7)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.vz' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_acc' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 8),
               "temperature_acc")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'temperature_acc' in position 9.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_acc' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 8)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.temperature_acc' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_acc' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 8);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId, 8);
         dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.temperature_acc' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_acc' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 8)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.temperature_acc' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_gyro' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 9),
               "temperature_gyro")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'temperature_gyro' in position 10.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_gyro' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 9)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.temperature_gyro' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_gyro' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 9);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId, 9);
         dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.temperature_gyro' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_gyro' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 9)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.temperature_gyro' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ultrasound' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 10),
               "ultrasound")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'ultrasound' in position 11.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ultrasound' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 10)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.ultrasound' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ultrasound' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 10);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          10); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.ultrasound' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.ultrasound' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 10)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.ultrasound' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_debut_echo' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 11),
               "us_debut_echo")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'us_debut_echo' in position 12.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_debut_echo' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 11)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_debut_echo' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_debut_echo' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 11);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          11); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_debut_echo' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_debut_echo' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 11)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_debut_echo' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_fin_echo' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 12),
               "us_fin_echo")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'us_fin_echo' in position 13.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_fin_echo' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 12)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_fin_echo' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_fin_echo' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 12);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          12); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_fin_echo' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_fin_echo' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 12)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_fin_echo' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_association_echo' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 13),
               "us_association_echo")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'us_association_echo' in position 14.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_association_echo' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 13)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_association_echo' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_association_echo' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 13);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          13); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_association_echo' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_association_echo' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 13)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_association_echo' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_distance_echo' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 14),
               "us_distance_echo")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'us_distance_echo' in position 15.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_distance_echo' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 14)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_distance_echo' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_distance_echo' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 14);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          14); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_distance_echo' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_distance_echo' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 14)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_distance_echo' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_time' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 15),
               "us_curve_time")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'us_curve_time' in position 16.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_time' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 15)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_curve_time' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_time' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 15);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          15); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_curve_time' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_time' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 15)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_curve_time' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_value' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 16),
               "us_curve_value")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'us_curve_value' in position 17.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_value' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 16)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_curve_value' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_value' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 16);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          16); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_curve_value' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_value' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 16)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_curve_value' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_ref' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 17),
               "us_curve_ref")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'us_curve_ref' in position 18.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_ref' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 17)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_curve_ref' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_ref' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 17);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          17); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_curve_ref' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.us_curve_ref' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 17)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.us_curve_ref' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.nb_echo' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 18), "nb_echo")
        !=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'nb_echo' in position 19.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.nb_echo' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 18)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.nb_echo' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.nb_echo' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 18);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          18); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.nb_echo' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.nb_echo' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 18)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.nb_echo' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.sum_echo' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 19), "sum_echo")
        !=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'sum_echo' in position 20.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.sum_echo' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 19)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint32"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.sum_echo' must have the same data type storage Id as an 'uint32' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.sum_echo' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 19);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          19); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.sum_echo' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.sum_echo' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 19)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.sum_echo' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.gradient' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 20), "gradient")
        !=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'gradient' in position 21.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.gradient' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 20)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "int16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.gradient' must have the same data type storage Id as an 'int16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.gradient' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 20);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          20); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.gradient' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.gradient' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 20)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.gradient' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.flag_echo_ini' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 21),
               "flag_echo_ini")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'flag_echo_ini' in position 22.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.flag_echo_ini' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 21)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.flag_echo_ini' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.flag_echo_ini' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 21);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          21); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.flag_echo_ini' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.flag_echo_ini' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 21)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.flag_echo_ini' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.pressure' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 22), "pressure")
        !=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'pressure' in position 23.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.pressure' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 22)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "int32"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.pressure' must have the same data type storage Id as an 'int32' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.pressure' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 22);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          22); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.pressure' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.pressure' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 22)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.pressure' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_pressure' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 23),
               "temperature_pressure")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'temperature_pressure' in position 24.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_pressure' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 23)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.temperature_pressure' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_pressure' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 23);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          23); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.temperature_pressure' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.temperature_pressure' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 23)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.temperature_pressure' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.mx' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 24), "mx")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'mx' in position 25.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.mx' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 24)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "int16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.mx' must have the same data type storage Id as an 'int16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.mx' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 24);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          24); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.mx' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.mx' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 24)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.mx' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.my' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 25), "my")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'my' in position 26.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.my' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 25)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "int16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.my' must have the same data type storage Id as an 'int16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.my' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 25);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          25); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.my' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.my' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 25)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.my' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.mz' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 26), "mz")!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'mz' in position 27.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.mz' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 26)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "int16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.mz' must have the same data type storage Id as an 'int16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.mz' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 26);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          26); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.mz' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.mz' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 26)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.mz' must be real.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.chksum' */
    if (strcmp((char *) ssGetBusElementName(S, __IMU_PacketsId, 27), "chksum")!=
        0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType 'IMU_Packets' must have the element 'chksum' in position 28.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.chksum' data type */
    if (dtaGetDataTypeStorageId(dta, bpath, ssGetBusElementDataType(S,
          __IMU_PacketsId, 27)) != dtaGetDataTypeStorageId(dta, bpath,
         dtaGetDataTypeId(dta, "uint16"))) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.chksum' must have the same data type storage Id as an 'uint16' has.");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.chksum' width */
    width = 1;
    dims = (int_T *) ssGetBusElementDimensions(S, __IMU_PacketsId, 27);
    for (dimIdx = 0; dimIdx < ssGetBusElementNumDimensions(S, __IMU_PacketsId,
          27); dimIdx++) {
      width *= dims[dimIdx];
    }

    if (width!=1) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.chksum' must have 1 element(s).");
      return;
    }

    /* Verify Bus/Struct element 'IMU_Packets.chksum' complexity */
    if (ssGetBusElementComplexSignal(S, __IMU_PacketsId, 27)!=0) {
      ssSetErrorStatus(S,
                       "The Bus/StructType element 'IMU_Packets.chksum' must be real.");
      return;
    }
  }
}

/* Function: GetRTWEnvironmentMode ======================================
 * Abstract:
 *    Must be called when ssRTWGenIsCodeGen(S)==true. This function
 *    returns the code generation mode:
 *      -1 if an error occurred
 *       0 for standalone code generation target
 *       1 for simulation target (Accelerator, RTW-SFcn,...)
 */
static int_T GetRTWEnvironmentMode(SimStruct *S)
{
  int_T status;
  mxArray *plhs[1];
  mxArray *prhs[1];
  int_T err;

  /*
   * Get the name of the Simulink block diagram
   */
  prhs[0] = mxCreateString(ssGetModelName(ssGetRootSS(S)));
  plhs[0] = NULL;

  /*
   * Call "isSimulationTarget = rtwenvironmentmode(modelName)" in MATLAB
   */
  mexSetTrapFlag(1);
  err = mexCallMATLAB(1, plhs, 1, prhs, "rtwenvironmentmode");
  mexSetTrapFlag(0);
  mxDestroyArray(prhs[0]);

  /*
   * Set the error status if an error occurred
   */
  if (err) {
    if (plhs[0]) {
      mxDestroyArray(plhs[0]);
      plhs[0] = NULL;
    }

    ssSetErrorStatus(S, "Unknown error during call to 'rtwenvironmentmode'.");
    return -1;
  }

  /*
   * Get the value returned by rtwenvironmentmode(modelName)
   */
  if (plhs[0]) {
    status = (int_T) (mxGetScalar(plhs[0]) != 0);
    mxDestroyArray(plhs[0]);
    plhs[0] = NULL;
  }

  return (status);
}

/*
 * Required S-function trailer
 */
#ifdef MATLAB_MEX_FILE
# include "simulink.c"
#else
# include "cg_sfun.h"
#endif
