% Copyright 2014 The MathWorks, Inc.
function [fitresult, gof] = createFit_Automate(TempMeasureRefined, GyroDrift_Roll,PlotName)
%CREATEFIT(TEMPMEASUREREFINED,GYRODRIFT_ROLL)
%  Create a fit.
%
%  Data for 'CurveFit_Bias' fit:
%      X Input : TempMeasureRefined
%      Y Output: GyroDrift_Roll
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Jul-2014 12:00:46


%% Fit: 'CurveFit_Bias'.
[xData, yData] = prepareCurveData( TempMeasureRefined, GyroDrift_Roll );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', PlotName );
h = plot( fitresult, xData, yData );
legend( h, 'GyroDrift_Roll vs. TempMeasureRefined', 'CurveFit_Bias', 'Location', 'NorthEast' );
% Label axes
xlabel( 'TempMeasureRefined' );
ylabel( 'GyroDrift_Roll' );
grid on


