#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE AR Drone 2 - Thread Timer Scheduler
#define MW_IP 192.168.1.1
#define MW_CLOCKING_CPUCLOCKRATEMHZ 800
#define MW_LINUX_BASERATETASKPRIORITY 40
#define MW_RUNTIME_BUILDACTION 1
#define MW_MULTI_TASKING_MODE 1
